name: 'Api build and deploy top app service https://rc-ca-webapi.azurewebsites.net/swagger/index.html'

on:
  workflow_dispatch:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' #default location app root
  AZURE_WEBAPP_NAME: RC-CA-WebAPI
  AZURE_WEBAPP_PROJECTNAME: RC.CA.WebApi


jobs:
  build:
    #if: "!contains(github.event.head_commit.message, 'skip ci')" ship if commit messsage contains skip ci text
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build '${{env.AZURE_WEBAPP_PROJECTNAME}}' --configuration Release
      
    - name: Test
      run: dotnet test
      
    - name: Publish
      run: dotnet publish '${{env.AZURE_WEBAPP_PROJECTNAME}}' -c Release -o '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp'
      
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        #slot-name 'development'
        publish-profile: ${{ secrets.AZURE_API_BUILD_PUBLISH_SECRET }}
        package: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp'
