name: Build a Docker image and Push it to ACR

on:
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  AZURE_CONTAINER_LOGIN_SERVER: 'rccacontainerregistry.azurecr.io'
  AZURE_APP_NAME: rccanotificationwebapi
  AZURE_DOCKER_FILE: RC.CA.Notification.WebApi/Dockerfile
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.AZURE_CONTAINER_LOGIN_SERVER}}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - run: |
          docker build --file ${{env.AZURE_DOCKER_FILE}} -t ${{env.AZURE_CONTAINER_LOGIN_SERVER}}/${{env.AZURE_APP_NAME}}:${{ github.sha }} .
          docker push ${{env.AZURE_CONTAINER_LOGIN_SERVER}}/${{env.AZURE_APP_NAME}}:${{ github.sha }}
