name: Scheduled monthly build 7.30

on:
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Running with deploy option ${{github.event.inputs.deploy}}"
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
